import { StyleSheet } from 'react-native';
import { FontFamily, FontSize } from '@shared/theme';

export const styles = StyleSheet.create({
  habitCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 16,
    padding: 20,
    elevation: 4,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.05,
    shadowRadius: 8,
    marginVertical: 6,
    marginHorizontal: 16,
  },
  mainContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  iconContainer: {
    width: 56,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  contentContainer: {
    flex: 1,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  habitTitle: {
    fontSize: FontSize.lg,
    fontFamily: FontFamily.semiBold,
    flex: 1,
  },
  statusBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 4,
  },
  priorityBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 4,
  },
  priorityText: {
    fontSize: 10,
    fontFamily: FontFamily.semiBold,
  },
  frequencyBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginRight: 8,
    marginBottom: 4,
  },
  frequencyText: {
    fontSize: 10,
    fontFamily: FontFamily.semiBold,
  },
  oneTimeBadge: {
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 8,
    marginBottom: 4,
  },
  oneTimeText: {
    fontSize: 10,
    fontFamily: FontFamily.semiBold,
  },
  statusDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    marginRight: 6,
  },
  statusText: {
    fontSize: FontSize.xs,
    fontFamily: FontFamily.semiBold,
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  streakContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FFF5F2',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  streakText: {
    marginLeft: 4,
    fontSize: FontSize.sm,
    fontFamily: FontFamily.semiBold,
    color: '#FF5722',
  },
  description: {
    fontSize: FontSize.sm,
    marginBottom: 16,
    lineHeight: 20,
  },
  cardFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  targetDaysContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  targetDaysText: {
    fontSize: FontSize.xs,
    marginLeft: 6,
  },
  addButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  highPriorityTag: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: '#FFEBEB',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderTopRightRadius: 16,
    borderBottomLeftRadius: 12,
  },
  highPriorityText: {
    fontSize: 9,
    fontFamily: FontFamily.semiBold,
    color: '#D32F2F',
    letterSpacing: 0.5,
  },
});
