export const STRINGS = {
  AUTH: {
    LABELS: {
      LOGIN_TITLE: 'Login',
      LOGIN_SUBTITLE: 'Sign in to access your habits and progress.',
      EMAIL_PLACEHOLDER: 'Email Address',
      PASSWORD_PLACEHOLDER: 'Password',
      SIGNING_IN: 'Signing in...',
      SIGN_IN_BUTTON: 'Sign In',
      OR: 'OR',
      GOOGLE_BUTTON: 'Continue with Google',
      DONT_HAVE_ACCOUNT: "Don't have an account? ",
      REGISTER_LINK: 'Sign Up',
    },
    ERRORS: {
      LOGIN: 'Unable to sign in. Please try again.',
      ALREADY_LOGGED_IN: 'You are already logged in.',
      INVALID_CREDENTIALS: 'Invalid email or password.',
      EMAIL_EXISTS: 'This email is already in use.',
      INVALID_EMAIL: 'The email address is invalid.',
      WEAK_PASSWORD: 'The password is too weak.',
      GENERIC: 'An error occurred. Please try again.',
    },
    LOGIN_SUCCESS: 'Logged in successfully! 👋',
    REGISTER_SUCCESS: 'Account created successfully! 🎉',
  },
  EXIT_APP: {
    TITLE: 'Exit App',
    MESSAGE: 'Are you sure you want to exit the app?',
    CONFIRM: 'Exit',
  },
  LOGOUT: {
    TITLE: 'Logout',
    MESSAGE: 'Are you sure you want to logout?',
    CONFIRM: 'Logout',
    CANCEL: 'Cancel',
  },
  HABITS: {
    DETAILS_TITLE: 'Habit Details',
    CREATE_TITLE: 'Create Habit',
    EDIT_TITLE: 'Edit Habit',
    LIST_TITLE: 'My Habits',
    ALL_TITLE: 'Habits',
    LIST: {
      WELCOME: 'Keep up the good work! 👋',
      ACTIVE_COUNT: (count: number) => `You have ${count} active habits today.`,
      EMPTY_STATE: 'No habits found for this day.',
      REFLECTION_TITLE: "Today's Reflection",
      REFLECTION_PLACEHOLDER: 'How did it go today? (Optional)',
      SAVE_REFLECTION: 'Save Reflection',
      STATS: 'Stats',
    },
    ALL_HABITS: {
      SEARCH_PLACEHOLDER: 'Search habits...',
      RESULTS_COUNT: (count: number) => `Found ${count} ${count === 1 ? 'habit' : 'habits'}`,
      CLEAR_FILTERS: 'Clear Filters',
      EMPTY_SEARCH: 'No habits match your filters.',
      EMPTY_ALL: 'No habits created yet. Pull down to refresh or create one!',
      CREATE_NEW: 'Create New Habit',
      FILTER_TITLE: 'Filters',
      RESET: 'Reset',
      CATEGORY: 'Category',
      PRIORITY: 'Priority',
      FREQUENCY: 'Frequency',
      TIME_OF_DAY: 'Time of Day',
      PREFERENCES: 'Type & Preferences',
      ONE_TIME_TASK: 'One-time Task',
      RECURRING_HABIT: 'Recurring Habit',
      FAVORITES: 'Favorites ❤️',
      SHOW_RESULTS: (count: number) => `Show ${count} results`,
    },
    FORM: {
      PLACEHOLDERS: {
        TITLE: 'Habit Title (e.g. Read 20 mins)',
        DESCRIPTION: 'What will you do? Why is this important?',
        NOTE: 'Add a note...',
        TARGET_MONTH: 'e.g. 10',
        GOAL: 'Long term goal (e.g. Healthier heart)',
        HOURS: 'Number of hours',
        MINUTES: 'Number of minutes',
        COUNT: 'Target count',
      },
      LABELS: {
        SECTION_DETAILS: 'Habit Details',
        SECTION_PRIORITY: 'Priority',
        SECTION_TIME: 'Time of Day',
        SECTION_FREQUENCY: 'Frequency',
        SECTION_FLEXIBLE_TARGET: 'Flexible Target (Optional)',
        SECTION_GOAL: 'Goal & Duration Type',
        GOAL_DESCRIPTION: 'Goal Description',
        DURATION_TYPE: 'Duration Type',
        TIMES_PER_MONTH: 'How many times per month?',
        NO_DATES_HINT: 'No dates selected. Add dates where you want to perform this habit.',
        FREQUENCY: {
          DAILY: 'Daily',
          WEEKLY: 'Weekly',
          MONTHLY: 'Monthly',
          QUARTERLY: 'Quarterly',
          HALF_YEARLY: 'Half-yearly',
          YEARLY: 'Yearly',
          CUSTOM: 'Custom',
        },
        TIME_OF_DAY: {
          MORNING: 'Morning',
          AFTERNOON: 'Afternoon',
          EVENING: 'Evening',
          NIGHT: 'Night',
          ANYTIME: 'Anytime',
        },
        DURATION: {
          HOURS: 'Hours',
          MINUTES: 'Minutes',
          COUNT: 'Count',
          NONE: 'None',
        },
        DURATION_LABELS: {
          HOURS: 'Target Hours',
          MINUTES: 'Target Minutes',
          COUNT: 'Target Count',
        },
        DURATION_HINT: "Tip: For more flexible scheduling, consider using the 'Custom' frequency in the section above.",
        TIMELINE: 'Timeline',
        TASK_DATE: 'Task Date',
        START_DATE: 'Start Date',
        END_DATE: 'End Date',
        NOT_SET: 'Not set',
        CLEAR_END_DATE: 'Clear End Date',
      },
    },
    VALIDATION: {
      TOO_SHORT: 'Too Short!',
      TITLE_REQUIRED: 'Title is required',
      DESCRIPTION_REQUIRED: 'Description is required',
      PRIORITY_REQUIRED: 'Priority is required',
      TIME_REQUIRED: 'Time of day is required',
      FREQUENCY_REQUIRED: 'Frequency is required',
      GOAL_TYPE_REQUIRED: 'Goal type is required',
      WEEK_LIMIT: 'Cannot exceed 7 days per week',
      MONTH_LIMIT: 'Cannot exceed 31 days per month',
      SELECT_DAY: 'Select at least one day',
      SELECT_DATE: 'Select at least one specific date',
      TARGET_REQUIRED: 'Target value is required',
      TARGET_NON_ZERO: 'Target must be greater than 0',
      HOUR_LIMIT: 'Hours cannot exceed 24',
    },
    LABELS: {
      CURRENT_STREAK: 'Current Streak',
      DAYS_COMPLETED: 'Days Completed',
      GOAL_TRACKING: 'Goal & Tracking',
      TARGET: 'Target',
      SELECTED_DAYS: 'Days',
      TIMELINE: 'Timeline',
      CREATED_ON: 'Created on:',
      STARTED_ON: 'Started on:',
      ENDS_ON: 'Ends on:',
      LAST_UPDATED: 'Last updated:',
      HISTORY: 'History',
      EDIT_HABIT: 'Edit Habit',
      MARK_DONE: 'Mark as Done',
      STATUS: 'Habit Status',
      ACTIVE: 'Active',
      PAUSED: 'Paused',
      COMPLETED: 'Completed',
      LOW: 'Low',
      MEDIUM: 'Medium',
      HIGH: 'High',
    },
    SAVE: {
      TITLE: 'Create Habit',
      MESSAGE: 'Ready to start your new habit journey?',
      CONFIRM: 'Create',
      SAVING: 'Checking...',
    },
    UPDATE: {
      TITLE: 'Update Habit',
      MESSAGE: 'Do you want to save the changes to this habit?',
      CONFIRM: 'Update',
      SAVING: 'Updating...',
    },
    DELETE: {
      TITLE: 'Delete Habit',
      MESSAGE:
        'Are you sure you want to delete this habit? This action cannot be undone and you will lose all progress recorded so far.',
      CONFIRM: 'Delete',
      CANCEL: 'Cancel',
    },
    DESCRIPTIONS: {
      EVERY_DAY: 'Every day',
      TIMES_PER_WEEK: (count: number) => `${count} times per week`,
      TIMES_PER_MONTH: (count: number) => `${count} times per month`,
      EVERY: 'Every ',
      OF_MONTH: ' of the month',
      OF_EVERY_3_MONTHS: (day: string) => `${day} of every 3 months`,
      OF_EVERY_6_MONTHS: (day: string) => `${day} of every 6 months`,
      EVERY_YEAR: (day: string, month: string) => `${day} of ${month} every year`,
      SPECIFIC_DATES: (count: number) => `${count} specific date${count > 1 ? 's' : ''}`,
      CUSTOM_SCHEDULE: 'Custom schedule',
      ONE_TIME: (month: string, day: number) => `One-time task on ${month} ${day}`,
    },
  },
  MONTHS: {
    SHORT: ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN', 'JUL', 'AUG', 'SEP', 'OCT', 'NOV', 'DEC'],
    FULL: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ],
  },
  DAYS: {
    SHORT: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    FULL: {
      Mon: 'Monday',
      Tue: 'Tuesday',
      Wed: 'Wednesday',
      Thu: 'Thursday',
      Fri: 'Friday',
      Sat: 'Saturday',
      Sun: 'Sunday',
    },
  },
};
